---
title: Current projects
---

In 2026, I'm focused on syntactic anaysis of historical languages. I'm using [DSPy](https://dspy.ai) to develop Python packages that leverage language models.

Language-specific models for analyzing syntax:


- [arsgrammatica](https://neelsmith.github.io/arsgrammatica/): a Python package leveraging LLMs with `dspy` to analyze the syntax of passages of Latin.
- [grammatike](https://neelsmith.github.io/grammatike/): a Python package leveraging LLMs with `dspy` to analyze the syntax of passages of ancient Greek.
- [diqduq](https://neelsmith.github.io/diqduq/): a Python package leveraging LLMs with `dspy` to analyze the syntax of passages of Biblical Hebrew.


A universal model of natural language syntax:

- [aat](https://neelsmith.github.io/aat/): an Agent-Action-Target model of natural-language syntax in Python.


Packages for extracting information from nlp analysis with spaCy:

- [udsyntax](https://neelsmith.github.io/udsyntax/): get Universal Dependency (syntactic) data from spaCy into a simple syntax graph format.
- [latincymorph](https://github.com/neelsmith/latincymorph): get morphological data from spaCy analysis of Latin texts into a structured object format.




## Adjacent projects

I'm beginning to apply this syntactic analysis in:

- a **digital Complutensian polyglot Bible**: digital resources for both experts and novices, supporting aligned multilingual reading 
- the **Homer Multitext project**:  a personal site about how I work with the Homer Multitext project’s digital archive

